services:
  - type: web
    name: okolea-backend
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: pnpm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: mongodb+srv://hingamax:m90pros%407@cluster0.cy1ftfw.mongodb.net/socket-database?retryWrites=true&w=majority
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://client-chi-rosy-78.vercel.app/
